const baseDeDatosProductos = [
    {
        'id': 1,
        'nombre': 'Camiseta PSG Títular',
        'categoria': 'Camisetas',
        'precio': 1200,
        'imagen': "../assets/products/camiseta-psg-suplente.png",
        'talle': '',
    },
    {
        'id': 2,
        'nombre': 'Camiseta Argentina 2021 Títular',
        'categoria': 'Camisetas',
        'precio': 1200,
        'imagen': "../assets/products/camiseta-argentina-titular.png",
        'talle': '',
    },
    {
        'id': 3,
        'nombre': 'Camiseta Bayer Munich 2021 Títular',
        'categoria': 'Camisetas',
        'precio': 1200,
        'imagen': "../assets/products/camiseta-bayer-munich-titular.png",
        'talle': '',
    },
    {
        'id': 4,
        'nombre': 'Camiseta River Plate 2021 Alternativa',
        'categoria': 'Camisetas',
        'precio': 1200,
        'imagen': "../assets/products/camiseta-river-plate-suplente.png",
        'talle': '',
    },
    {
        'id': 5,
        'nombre': 'Buzo Boca Juniors',
        'categoria': 'Buzos',
        'precio': 1800,
        'imagen': "../assets/products/buzo-boca-juniors-blanco.png",
        'talle': '',
    },
    {
        'id': 6,
        'nombre': 'Campera Argentina',
        'categoria': 'Camperas',
        'precio': 1700,
        'imagen': "../assets/products/campera-argentina.png",
        'talle': '',
    },
    {
        'id': 7,
        'nombre': 'Campera PSG',
        'categoria': 'Camperas',
        'precio': 1700,
        'imagen': "../assets/products/campera-psg.png",
        'talle': '',
    },
    {
        'id': 8,
        'nombre': 'Camiseta Red Bull',
        'categoria': 'Camisetas',
        'precio': 1200,
        'imagen': "../assets/products/camiseta-red-bull.png",
        'talle': '',
    },
];
